-- Down migration for 20250826_saas_ml_features.sql
DROP INDEX IF EXISTS idx_saas_tenants_tenant_id;
DROP INDEX IF EXISTS idx_saas_tenants_status;
DROP INDEX IF EXISTS idx_saas_tenants_tier;
DROP INDEX IF EXISTS idx_saas_tenants_trial_ends;
DROP INDEX IF EXISTS idx_api_request_logs_tenant;
DROP INDEX IF EXISTS idx_api_request_logs_timestamp;
DROP INDEX IF EXISTS idx_webhook_deliveries_tenant;
DROP INDEX IF EXISTS idx_ml_models_type;
DROP INDEX IF EXISTS idx_ml_models_active;
DROP INDEX IF EXISTS idx_ml_models_name;
DROP INDEX IF EXISTS idx_detected_patterns_type;
DROP INDEX IF EXISTS idx_detected_patterns_confidence;
DROP INDEX IF EXISTS idx_detected_patterns_last_seen;
DROP INDEX IF EXISTS idx_ml_predictions_model;
DROP INDEX IF EXISTS idx_ml_predictions_type;
DROP INDEX IF EXISTS idx_ml_predictions_valid;
DROP INDEX IF EXISTS idx_intelligent_filters_active;
DROP INDEX IF EXISTS idx_intelligent_filters_confidence;
DROP INDEX IF EXISTS idx_events_tenant_id;
DROP INDEX IF EXISTS idx_subscriptions_tenant_id;
DROP INDEX IF EXISTS idx_metric_history_subscription;
DROP INDEX IF EXISTS idx_metric_history_tenant;
DROP TRIGGER IF EXISTS update_saas_tenants_updated_at ON saas_tenants;
DROP TRIGGER IF EXISTS update_ml_models_updated_at ON ml_models;
DROP TRIGGER IF EXISTS update_intelligent_filters_updated_at ON intelligent_filters;
DROP FUNCTION IF EXISTS update_updated_at_column() CASCADE;
DROP TABLE IF EXISTS saas_tenants CASCADE;
DROP TABLE IF EXISTS api_request_logs CASCADE;
DROP TABLE IF EXISTS webhook_deliveries CASCADE;
DROP TABLE IF EXISTS ml_models CASCADE;
DROP TABLE IF EXISTS detected_patterns CASCADE;
DROP TABLE IF EXISTS ml_predictions CASCADE;
DROP TABLE IF EXISTS intelligent_filters CASCADE;
DROP TABLE IF EXISTS metric_history CASCADE;
ALTER TABLE events DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE subscriptions DROP COLUMN IF EXISTS tenant_id;
DROP TYPE IF EXISTS subscription_tier;
DROP TYPE IF EXISTS tenant_status;
