//! Database Configuration Tuning & Best Practices (Issue #824).
//!
//! A PGTune-style advisor that turns host resource inputs (memory, CPU count,
//! expected connection count, storage type) into recommended `postgresql.conf`
//! values for an OLTP-style workload like Soroban Pulse's event indexing and
//! query API.
//!
//! These are starting points, not a substitute for workload-specific
//! profiling. Always validate with `pg_stat_statements` and `EXPLAIN ANALYZE`
//! after applying — see [`docs/performance-tuning.md`] and
//! [`docs/database-configuration-tuning.md`] for the full picture, including
//! the SQLx connection pool settings (`DB_MAX_CONNECTIONS` /
//! `DB_MIN_CONNECTIONS`), which this module does not cover — see
//! `crate::pool_management` for that.

use std::fmt;

/// Hosts below this size still get a recommendation, floored here so the
/// resulting numbers stay sane rather than degenerating toward zero.
const MIN_MEMORY_MB: u64 = 256;
const MAX_SANE_CONNECTIONS: u32 = 5000;

/// Inputs describing the target PostgreSQL host.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PgTuningInput {
    pub total_memory_mb: u64,
    pub cpu_count: u32,
    pub max_connections: u32,
    pub storage_is_ssd: bool,
}

/// Why a [`PgTuningInput`] was rejected.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PgTuningInputError {
    ZeroMemory,
    ZeroCpu,
    ZeroConnections,
    ConnectionsTooHigh(u32),
}

impl fmt::Display for PgTuningInputError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::ZeroMemory => write!(f, "total_memory_mb must be greater than zero"),
            Self::ZeroCpu => write!(f, "cpu_count must be greater than zero"),
            Self::ZeroConnections => write!(f, "max_connections must be greater than zero"),
            Self::ConnectionsTooHigh(n) => write!(
                f,
                "max_connections {} exceeds the sane upper bound of {}",
                n, MAX_SANE_CONNECTIONS
            ),
        }
    }
}

impl std::error::Error for PgTuningInputError {}

pub fn validate_tuning_input(input: &PgTuningInput) -> Result<(), PgTuningInputError> {
    if input.total_memory_mb == 0 {
        return Err(PgTuningInputError::ZeroMemory);
    }
    if input.cpu_count == 0 {
        return Err(PgTuningInputError::ZeroCpu);
    }
    if input.max_connections == 0 {
        return Err(PgTuningInputError::ZeroConnections);
    }
    if input.max_connections > MAX_SANE_CONNECTIONS {
        return Err(PgTuningInputError::ConnectionsTooHigh(
            input.max_connections,
        ));
    }
    Ok(())
}

/// One recommended `postgresql.conf` parameter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PgConfigRecommendation {
    pub parameter: String,
    pub recommended_value: String,
    pub rationale: String,
}

impl PgConfigRecommendation {
    fn new(parameter: &str, recommended_value: String, rationale: &str) -> Self {
        Self {
            parameter: parameter.to_string(),
            recommended_value,
            rationale: rationale.to_string(),
        }
    }
}

/// A full set of recommendations for one host profile.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PgTuningReport {
    pub recommendations: Vec<PgConfigRecommendation>,
}

impl PgTuningReport {
    pub fn get(&self, parameter: &str) -> Option<&PgConfigRecommendation> {
        self.recommendations
            .iter()
            .find(|r| r.parameter == parameter)
    }

    /// Render as a ready-to-review `postgresql.conf` snippet.
    pub fn render_config_snippet(&self) -> String {
        let mut out = String::from("# Generated by db_config_advisor — review before applying.\n");
        for rec in &self.recommendations {
            out.push_str(&format!(
                "\n# {}\n{} = {}\n",
                rec.rationale, rec.parameter, rec.recommended_value
            ));
        }
        out
    }
}

/// Compute recommended `postgresql.conf` values for the given host profile.
///
/// Formulas follow the well-known PGTune heuristics for a "Mixed" OLTP
/// workload: `shared_buffers` at ~25% of RAM, `effective_cache_size` at ~75%,
/// `work_mem` sized so `max_connections` concurrent sort/hash operations fit
/// within the remaining memory, and I/O cost parameters set for SSD vs. spinning
/// disk. Because they are heuristics, treat the result as a starting
/// configuration to validate against your actual query workload, not a final
/// answer.
pub fn recommend_postgres_config(
    input: &PgTuningInput,
) -> Result<PgTuningReport, PgTuningInputError> {
    validate_tuning_input(input)?;

    let mem = input.total_memory_mb.max(MIN_MEMORY_MB);

    let shared_buffers_mb = (mem / 4).max(16);
    let effective_cache_size_mb = (mem * 3 / 4).max(shared_buffers_mb);
    let maintenance_work_mem_mb = (mem / 16).clamp(16, 2048);
    let wal_buffers_mb = (shared_buffers_mb / 32).clamp(1, 16);

    let workable_mem_mb = mem.saturating_sub(shared_buffers_mb).max(mem / 4);
    let work_mem_mb = (workable_mem_mb / (u64::from(input.max_connections) * 3)).clamp(1, 256);

    let (random_page_cost, random_page_cost_reason) = if input.storage_is_ssd {
        (
            "1.1",
            "SSD/NVMe storage: random and sequential I/O cost are similar.",
        )
    } else {
        (
            "4.0",
            "Spinning disk: random I/O is markedly more expensive than sequential.",
        )
    };
    let (effective_io_concurrency, io_concurrency_reason) = if input.storage_is_ssd {
        (
            "200",
            "SSDs handle many concurrent I/O requests efficiently.",
        )
    } else {
        (
            "2",
            "Spinning disks benefit little from concurrent I/O requests.",
        )
    };

    let max_worker_processes = input.cpu_count.max(2);
    let max_parallel_workers_per_gather = (input.cpu_count / 2).clamp(1, 4);
    let max_parallel_workers = input.cpu_count.max(2);

    let recommendations = vec![
        PgConfigRecommendation::new(
            "shared_buffers",
            format!("{}MB", shared_buffers_mb),
            "~25% of RAM: PostgreSQL's dedicated shared memory cache for table and index pages.",
        ),
        PgConfigRecommendation::new(
            "effective_cache_size",
            format!("{}MB", effective_cache_size_mb),
            "~75% of RAM: tells the planner how much total caching (shared_buffers + OS page cache) to expect when choosing between an index scan and a sequential scan.",
        ),
        PgConfigRecommendation::new(
            "maintenance_work_mem",
            format!("{}MB", maintenance_work_mem_mb),
            "Memory for VACUUM, CREATE INDEX, and similar maintenance operations, capped at 2GB — larger values rarely help further.",
        ),
        PgConfigRecommendation::new(
            "work_mem",
            format!("{}MB", work_mem_mb),
            "Per sort/hash operation memory, sized so max_connections concurrent operations do not collectively exceed available RAM.",
        ),
        PgConfigRecommendation::new(
            "wal_buffers",
            format!("{}MB", wal_buffers_mb),
            "WAL write buffer; scales with shared_buffers up to the 16MB point past which more rarely helps.",
        ),
        PgConfigRecommendation::new(
            "max_connections",
            input.max_connections.to_string(),
            "Matches the expected number of concurrent connections. Prefer PgBouncer over raising this further — see docs/performance-tuning.md.",
        ),
        PgConfigRecommendation::new(
            "random_page_cost",
            random_page_cost.to_string(),
            random_page_cost_reason,
        ),
        PgConfigRecommendation::new(
            "effective_io_concurrency",
            effective_io_concurrency.to_string(),
            io_concurrency_reason,
        ),
        PgConfigRecommendation::new(
            "max_worker_processes",
            max_worker_processes.to_string(),
            "At least one background worker slot per CPU core.",
        ),
        PgConfigRecommendation::new(
            "max_parallel_workers_per_gather",
            max_parallel_workers_per_gather.to_string(),
            "Half the CPU cores (capped at 4) so a single query cannot monopolize every core.",
        ),
        PgConfigRecommendation::new(
            "max_parallel_workers",
            max_parallel_workers.to_string(),
            "Total parallel worker budget across all concurrent queries.",
        ),
        PgConfigRecommendation::new(
            "checkpoint_completion_target",
            "0.9".to_string(),
            "Spreads checkpoint I/O across 90% of the checkpoint interval, avoiding write spikes. Not resource-dependent.",
        ),
    ];

    Ok(PgTuningReport { recommendations })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn input(memory_mb: u64, cpu: u32, connections: u32, ssd: bool) -> PgTuningInput {
        PgTuningInput {
            total_memory_mb: memory_mb,
            cpu_count: cpu,
            max_connections: connections,
            storage_is_ssd: ssd,
        }
    }

    #[test]
    fn validate_rejects_zero_memory() {
        let err = validate_tuning_input(&input(0, 4, 100, true)).unwrap_err();
        assert_eq!(err, PgTuningInputError::ZeroMemory);
    }

    #[test]
    fn validate_rejects_zero_cpu() {
        let err = validate_tuning_input(&input(8192, 0, 100, true)).unwrap_err();
        assert_eq!(err, PgTuningInputError::ZeroCpu);
    }

    #[test]
    fn validate_rejects_zero_connections() {
        let err = validate_tuning_input(&input(8192, 4, 0, true)).unwrap_err();
        assert_eq!(err, PgTuningInputError::ZeroConnections);
    }

    #[test]
    fn validate_rejects_excessive_connections() {
        let err = validate_tuning_input(&input(8192, 4, 10_000, true)).unwrap_err();
        assert_eq!(err, PgTuningInputError::ConnectionsTooHigh(10_000));
    }

    #[test]
    fn recommend_config_matches_expected_formulas_for_8gb_host() {
        let report = recommend_postgres_config(&input(8192, 4, 100, true)).unwrap();

        assert_eq!(
            report.get("shared_buffers").unwrap().recommended_value,
            "2048MB"
        );
        assert_eq!(
            report
                .get("effective_cache_size")
                .unwrap()
                .recommended_value,
            "6144MB"
        );
        assert_eq!(
            report
                .get("maintenance_work_mem")
                .unwrap()
                .recommended_value,
            "512MB"
        );
        assert_eq!(report.get("wal_buffers").unwrap().recommended_value, "16MB");
        assert_eq!(report.get("work_mem").unwrap().recommended_value, "20MB");
        assert_eq!(
            report.get("max_connections").unwrap().recommended_value,
            "100"
        );
    }

    #[test]
    fn ssd_and_hdd_recommend_different_io_settings() {
        let ssd = recommend_postgres_config(&input(8192, 4, 100, true)).unwrap();
        let hdd = recommend_postgres_config(&input(8192, 4, 100, false)).unwrap();

        assert_eq!(
            ssd.get("random_page_cost").unwrap().recommended_value,
            "1.1"
        );
        assert_eq!(
            hdd.get("random_page_cost").unwrap().recommended_value,
            "4.0"
        );
        assert_eq!(
            ssd.get("effective_io_concurrency")
                .unwrap()
                .recommended_value,
            "200"
        );
        assert_eq!(
            hdd.get("effective_io_concurrency")
                .unwrap()
                .recommended_value,
            "2"
        );
    }

    #[test]
    fn maintenance_work_mem_caps_at_2gb_for_huge_hosts() {
        // 128GB host: mem/16 = 8192MB, which must clamp down to the 2048MB cap.
        let report = recommend_postgres_config(&input(131_072, 32, 200, true)).unwrap();
        assert_eq!(
            report
                .get("maintenance_work_mem")
                .unwrap()
                .recommended_value,
            "2048MB"
        );
    }

    #[test]
    fn wal_buffers_caps_at_16mb() {
        let report = recommend_postgres_config(&input(131_072, 32, 200, true)).unwrap();
        assert_eq!(report.get("wal_buffers").unwrap().recommended_value, "16MB");
    }

    #[test]
    fn tiny_host_still_produces_sane_nonzero_recommendations() {
        let report = recommend_postgres_config(&input(100, 1, 5, true)).unwrap();
        for rec in &report.recommendations {
            assert!(
                !rec.recommended_value.trim_end_matches("MB").is_empty(),
                "empty recommended value for {}",
                rec.parameter
            );
        }
    }

    #[test]
    fn parallel_workers_scale_with_cpu_count_and_cap_per_gather_at_4() {
        let report = recommend_postgres_config(&input(8192, 16, 100, true)).unwrap();
        assert_eq!(
            report
                .get("max_worker_processes")
                .unwrap()
                .recommended_value,
            "16"
        );
        assert_eq!(
            report
                .get("max_parallel_workers_per_gather")
                .unwrap()
                .recommended_value,
            "4"
        );
    }

    #[test]
    fn render_config_snippet_includes_every_parameter() {
        let report = recommend_postgres_config(&input(8192, 4, 100, true)).unwrap();
        let snippet = report.render_config_snippet();
        for rec in &report.recommendations {
            assert!(
                snippet.contains(&format!("{} = {}", rec.parameter, rec.recommended_value)),
                "snippet missing line for {}",
                rec.parameter
            );
        }
    }

    #[test]
    fn pg_tuning_input_error_display_is_human_readable() {
        assert_eq!(
            PgTuningInputError::ZeroMemory.to_string(),
            "total_memory_mb must be greater than zero"
        );
        assert!(PgTuningInputError::ConnectionsTooHigh(9999)
            .to_string()
            .contains("9999"));
    }
}
